include $(THEOS)/makefiles/common.mk
TOOL_NAME = tunefetchd
tunefetchd_FILES = main.m
tunefetchd_FRAMEWORKS = Foundation SystemConfiguration
tunefetchd_CFLAGS = -fobjc-arc
include $(THEOS_MAKE_PATH)/tool.mk
