include $(THEOS)/makefiles/common.mk
BUNDLE_NAME = TuneFetchPrefs
TuneFetchPrefs_FILES = TFPRootListController.m
TuneFetchPrefs_INSTALL_PATH = /Library/PreferenceBundles
TuneFetchPrefs_FRAMEWORKS = UIKit
TuneFetchPrefs_PRIVATE_FRAMEWORKS = Preferences
TuneFetchPrefs_CFLAGS = -fobjc-arc
include $(THEOS_MAKE_PATH)/bundle.mk
